typesafehub/akka-contrib-extra

src/main/scala/akka/contrib/datareplication/ORMultiMap.scala, src/test/scala/akka/contrib/datareplication/ORMultiMapSpec.scala
In addition the removeBindings api call has been removed in favour of using the newly introduced get, put and remove map level operations.
=> Enhanced API and added a spec for ORMultiMap

build.sbt, project/Build.scala, project/Dependencies.scala, project/plugins.sbt, src/main/scala/akka/contrib/http/Directives.scala, src/test/scala/akka/contrib/http/DirectivesSpec.scala, version.sbt
As I am not able to release to `typesafe-releases` repo and this is a public project, I configured release to bintray. Now every member of [akka-contrib-extra](https://bintray.com/akka-contrib-extra) bintray organization can cut a release of this library. Release process is still the same using `sbt-release` plugin.
=> Add accept and parameterList directives

.travis.yml, project/Build.scala, src/main/scala/akka/contrib/process/BlockingProcess.scala
Also sbt-typesafe-conductr relies on this being 1.6.
=> Targeting 1.6 as this is the baseline for Akka 2.3

project/Dependencies.scala, src/main/scala/akka/contrib/stream/SourceInputStream.scala, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
Using `merge.in(...)` instead of `merge` because of https://github.com/akka/akka/issues/16997
=> Upgrade to akka-streams 1.0-M4

src/main/scala/akka/contrib/stream/pattern/reconnect/ReconnectingStreamHttp.scala, src/main/scala/akka/contrib/stream/pattern/reconnect/ReconnectingStreamTcp.scala, src/main/scala/akka/contrib/stream/pattern/reconnect/Reconnector.scala, src/main/scala/akka/contrib/stream/pattern/reconnect/package.scala, src/test/scala/akka/contrib/stream/pattern/reconnect/ReconnectingStreamHttpSpec.scala, src/test/scala/akka/contrib/stream/pattern/reconnect/ReconnectingStreamTcpSpec.scala
* reconnection APIs look now more like their normal counterparts - with the onConnect being given a new flow for each connection, they should materialize it
* http now actually reconnects; added tests as well
* reconnecting tcp / http delegate *all* params that may be passed into the normal outgoingConnection method. 
* better names for reconnection actors - still top level though, would be nice to have them move under a parent at some point.
* resolves https://github.com/typesafehub/akka-contrib-extra/issues/21
=> + improvements in reconnection utilities

src/main/scala/akka/contrib/process/BlockingProcess.scala, src/test/resources/sleep.sh, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
An actor has been introduced that will ensure a stream is closed if its parent is told to stop. Any other thread blocking on a read (for example) for the same stream should be unblocked by this action.
Fixes #24 and replaces #26
=> Stream closer

project/Dependencies.scala, src/test/scala/akka/contrib/stream/pattern/reconnect/ReconnectingStreamHttpSpec.scala, src/test/scala/akka/contrib/stream/pattern/reconnect/ReconnectingStreamTcpSpec.scala
`ReconnectingStreamHttpSpec` fails now, succeeded under M4. I wonder whether we need that feature at all, since we found an alternative approach to reconnecting for ConductR. I'd rather not include an unused feature, because unused is sort of untested.
As I'll be on vacation next week, I'll leave this one for you ...
=> WIP - DON'T MERGE: Upgrade to akka-stream/http 1.0-M5

src/main/scala/akka/contrib/process/BlockingProcess.scala, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala, src/test/scala/akka/contrib/process/package.scala
In addition the blocking process actor now ensures that its messages may only be sent to its parent, and not any other type of actor. This is because the actor publishers sent as part of the start message are not serialisable.
Contributes toward: https://github.com/typesafehub/conductr/issues/512
=> Added NoSerializationVerificationNeeded marker

.travis.yml, project/Dependencies.scala, src/main/scala/akka/contrib/http/Directives.scala, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
Migrate to Akka Streams and HTTP 2.0-M2
- Implement necessary modification to support Akka Streams and HTTP 2.0-M2
- Remove support for Java 6
=> Akka streams 2 upgrade

project/Dependencies.scala, src/main/scala/akka/contrib/process/BlockingProcess.scala
As part of upgrade ensure stdin, stdout, and stderr streams are being
executed with the same dispatcher as BlockingProcess
Default behaviour of Akka Streams since 2.0.3 onwards is to setup
i/o and file related streams to use default blocking i/o dispatcher
=> Upgrade akka streams and http to 2.0.3

project/Dependencies.scala
A binary compat changed occurred with Akka 2.4.3 w.r.t. optionalHeaderValueByType
=> Use the latest Akka

src/main/resources/reference.conf, src/main/scala/akka/contrib/process/BlockingProcess.scala, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
The BlockingProcess actor's dispatcher was leveraged for use by various IO operations within it. For some undiscovered reason, this led the BlockingProcess to become blocked at around the minimum number of threads per the core setting of its ThreadPoolExecutor (21).
I was able to create a new test that started up 100 processes, and therefore 300 threads on a dedicated dispatcher. Without the changes to the BlockingProcess actor i.e. with the actor sharing its TPE with the stdio stream sources and sinks, the test often failed and hung. With the changes where the TPE is dedicated to the IO, and the BlockingProcess actor resides on the default dispatcher, I was unable to reproduce the issue.
In addition, having a dispatcher dedicated to the actor's IO feels correct from a design standpoint. …
=> Avoid using the BlockingProcess dispatcher for IO

build.sbt, project/Dependencies.scala, src/main/scala/akka/contrib/actor/EmptyActor.scala, src/main/scala/akka/contrib/cluster/ddata/ORMapState.scala, src/main/scala/akka/contrib/cluster/ddata/ORMultiMapState.scala, src/main/scala/akka/contrib/cluster/ddata/ORSetState.scala, src/main/scala/akka/contrib/cluster/ddata/ReplicatingActor.scala, src/test/scala/akka/contrib/cluster/ddata/ORMapStateSpec.scala, src/test/scala/akka/contrib/cluster/ddata/ORMultiMapStateSpec.scala, src/test/scala/akka/contrib/cluster/ddata/ORSetStateSpec.scala, src/test/scala/akka/contrib/cluster/ddata/StateSpec.scala, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
Introduce helpers for Akka Distributed Data
- Introduce `ReplicatingActor` to provide stackable base behaviour to handle replicated state.
- Introduce `ORMapState`, `ORMultiMapState`, and `ORSetState` to help manage changes within `ORMap`, `ORMultiMap`, and `ORSet` respectively.
Also:
- Upgrade Akka to 2.4.10
- Introduce EmptyActor to help with applying stackable traits
=> Introduce Akka Distributed Data helper classes

src/main/resources/reference.conf
Use a fixed pool size to support 50 processes at maximum.
The 50 processes number is selected as it will consume `~25MiB` of heap.
=> Fix Blocking Dispatcher's configuration - Fixes #58

src/main/resources/reference.conf, src/main/scala/akka/contrib/process/BlockingProcess.scala, src/test/resources/loop.sh, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
This PR modifies `BlockingProcess` in a few ways:
Periodically we check `Process.isAlive()` via sending `Inspect` to `ProcessDestroyer`. Prior to this, we would only be notified if a process exited if its stdout and stderr file descriptors had exited. This is incorrect since these descriptors can live on beyond the execution of a process (via forking).
`Destroy` and `DestroyForcibly` now result in calls to `Process.destroy()` or `Process.destroyForcibly()`, respectively delivering a `SIGTERM` or `SIGKILL`, on UNIX at least - https://github.com/frohoff/jdk8u-jdk/blob/da0da73ab82ed714
When `stdout` or `stderr` exit, we fire an `Inspect` which allows us to exit in a quick manner in the ideal case, without having to wait for the next poll.
I think this is a quite safe implementation, and a …
=> BlockingProcess modified to poll isAlive() to determine if a process has exited.

src/main/resources/reference.conf, src/main/scala/akka/contrib/process/BlockingProcess.scala, src/test/resources/loop.sh, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
This is a cherry-pick of #57, the `isAlive` polling for `BlockingProcess`, to 3.0 branch (Akka 2.4)
=> [3.0] Cherry-pick #57 (isAlive)

project/Build.scala, project/build.properties, project/plugins.sbt
this will make it easier to keep this repo in the Scala
community build, since the newer sbt-bintray version is
dbuild-compatible
the sbt version bump also helps ensure community build friendliness
=> upgrade to much newer sbt-bintray version

build.sbt, project/Dependencies.scala, src/main/resources/reference.conf, src/main/scala/akka/contrib/process/BlockingProcess.scala, src/main/scala/akka/contrib/process/NonBlockingProcess.scala, src/test/resources/loop.sh, src/test/scala/akka/contrib/process/NonBlockingProcessSpec.scala
Utilises NuProcess in order to provide a non-blocking process implementation for Windows, OS X and Linux.
Authors: @longshorej and @huntc
=> Provide a non-blocking process implementation

src/main/resources/reference.conf, src/main/scala/akka/contrib/process/NonBlockingProcess.scala, src/test/scala/akka/contrib/process/BlockingProcessSpec.scala
I had previously thought that NuProcess handled back-pressure. As per https://github.com/brettwooldridge/NuProcess/issues/77, it doesn't appear so. Hence, I'm reverting the code to use a Source.queue and managing a 64KiB buffer directly.
If NuProcess ever does handle back-pressure then the PublishIfAvailable source could make a come-back. It was working beautifully. :-)
Requires cherry picking to master.
=> No back pressure in NuProcess

src/main/scala/akka/contrib/process/NonBlockingProcess.scala, src/test/scala/akka/contrib/process/NonBlockingProcessSpec.scala
Firstly, thanks for the NonBlockingProcess actor - this is exactly what I was looking for. Realize it's pretty bleeding edge but I'd love to help getting it stable.
The process I was trying to wrap takes input on stdin, and waits for EOF before outputting to stdout and terminiating - but using the actor the process was hanging because stdin wasn't being closed.
I found the NuProcess.closeStdin API, and sure enough hooking that into the Sink completion did the trick.
=> Close process stdin when the stream completes 
